name: Assign Reviewers

on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  add-reviewers:
    if: github.event.pull_request.draft == false
    name: Add Reviewers
    runs-on: ubuntu-latest
    steps:
      - name: Auto Assign Action
        uses: kentaro-m/auto-assign-action@v1.1.2
        with:
          configuration-path: '.github/workflows/reviewers.yml'
